// Generated from: features\GiftVoucher.feature
import { test } from "playwright-bdd";

test.describe('Gift Voucher Purchase', () => {
  test.describe.configure({"timeout":180000});

  test.beforeEach('Background', async ({ Given, page }, testInfo) => { if (testInfo.error) return;
    await Given('user navigates to the Phorest demo voucher page', null, { page }); 
  });
  
  test('Successfully purchase a €50 gift voucher', { tag: ['@GiftVoucher', '@timeout:180000', '@smoke', '@happy-path'] }, async ({ When, Then, And, page }) => { 
    await When('user selects a voucher amount of "€50"', null, { page }); 
    await And('user verifies \'Send to me\' tab is selected', null, { page }); 
    await And('user enters email, forename "Phorest" and surname "Test"', null, { page }); 
    await And('user proceeds to the summary page to confirm details', null, { page }); 
    await And('user enters card number "4111 1111 1111 1111", expiry "12/26", CVC "999"', null, { page }); 
    await Then('the confirmation page should display the voucher value and number', null, { page }); 
    await And('the user should receive a voucher email with a purchase receipt', null, { page }); 
  });

  test('Successfully purchase a €100 gift voucher for someone else with personalised message', { tag: ['@GiftVoucher', '@timeout:180000', '@happy-path'] }, async ({ When, Then, And, page }) => { 
    await When('user selects a voucher amount of "€100"', null, { page }); 
    await And('user selects \'Send to someone else\' tab', null, { page }); 
    await And('user enters email, forename "Phorest", surname "Test", recipient email and a message', null, { page }); 
    await And('user proceeds to the summary page to confirm details', null, { page }); 
    await And('user enters card number "4111 1111 1111 1111", expiry "12/26", CVC "999"', null, { page }); 
    await Then('the confirmation page should display the voucher value and number', null, { page }); 
    await And('the user should receive a voucher email with a purchase receipt', null, { page }); 
  });

  test('Successfully purchase a €150 gift voucher for someone else without personalised message', { tag: ['@GiftVoucher', '@timeout:180000', '@happy-path'] }, async ({ When, Then, And, page }) => { 
    await When('user selects a voucher amount of "€150"', null, { page }); 
    await And('user selects \'Send to someone else\' tab', null, { page }); 
    await And('user enters email, forename "Phorest", surname "Test" and recipient email without a message', null, { page }); 
    await And('user proceeds to the summary page to confirm details', null, { page }); 
    await And('user enters card number "4111 1111 1111 1111", expiry "12/26", CVC "999"', null, { page }); 
    await Then('the confirmation page should display the voucher value and number', null, { page }); 
    await And('the user should receive a voucher email with a purchase receipt', null, { page }); 
  });

  test('Successfully purchase a custom voucher amount', { tag: ['@GiftVoucher', '@timeout:180000', '@happy-path'] }, async ({ When, Then, And, page }) => { 
    await When('user selects a custom voucher amount of "€200"', null, { page }); 
    await And('user verifies \'Send to me\' tab is selected', null, { page }); 
    await And('user enters email, forename "Phorest" and surname "Test"', null, { page }); 
    await And('user proceeds to the summary page to confirm details', null, { page }); 
    await And('user enters card number "4111 1111 1111 1111", expiry "12/26", CVC "999"', null, { page }); 
    await Then('the confirmation page should display the voucher value and number', null, { page }); 
    await And('the user should receive a voucher email with a purchase receipt', null, { page }); 
  });

  test('User can edit gift voucher details from the summary page before payment', { tag: ['@GiftVoucher', '@timeout:180000', '@happy-path'] }, async ({ When, Then, And, page }) => { 
    await When('user selects a voucher amount of "€50"', null, { page }); 
    await And('user verifies \'Send to me\' tab is selected', null, { page }); 
    await And('user enters email, forename "Phorest" and surname "Test"', null, { page }); 
    await And('user proceeds to the summary page, clicks edit and updates the voucher amount to be "€100"', null, { page }); 
    await And('user enters card number "4111 1111 1111 1111", expiry "12/26", CVC "999"', null, { page }); 
    await Then('the confirmation page should display the voucher value and number', null, { page }); 
    await And('the user should receive a voucher email with a purchase receipt', null, { page }); 
  });

  test('User cannot proceed with invalid email format', { tag: ['@GiftVoucher', '@timeout:180000', '@validation'] }, async ({ When, Then, And, page }) => { 
    await When('user selects a voucher amount of "€50"', null, { page }); 
    await And('user verifies \'Send to me\' tab is selected', null, { page }); 
    await And('user enters invalid email "invalid-email", forename "Phorest" and surname "Test"', null, { page }); 
    await Then('an error message should be displayed indicating the email format is invalid', null, { page }); 
    await And('the user should not be able to proceed to the summary page', null, { page }); 
  });

  test('User cannot proceed without required recipient fields', { tag: ['@GiftVoucher', '@timeout:180000', '@validation'] }, async ({ When, Then, And, page }) => { 
    await When('user selects a voucher amount of "€100"', null, { page }); 
    await And('user selects \'Send to someone else\' tab', null, { page }); 
    await Then('the user should not be able to proceed to the summary page', null, { page }); 
  });

  test('User cannot proceed when a custom amount below minimum value is entered', { tag: ['@GiftVoucher', '@timeout:180000', '@validation'] }, async ({ When, Then, And, page }) => { 
    await When('user selects a custom voucher amount of "€10"', null, { page }); 
    await And('user verifies \'Send to me\' tab is selected', null, { page }); 
    await And('user enters email, forename "Phorest" and surname "Test"', null, { page }); 
    await Then('an error message should be displayed indicating the custom amount is invalid', null, { page }); 
    await And('the user should not be able to proceed to the summary page', null, { page }); 
  });

  test('Payment fails with invalid card number', { tag: ['@GiftVoucher', '@timeout:180000', '@negative'] }, async ({ When, Then, And, page }) => { 
    await When('user selects a voucher amount of "€50"', null, { page }); 
    await And('user verifies \'Send to me\' tab is selected', null, { page }); 
    await And('user enters email, forename "Phorest" and surname "Test"', null, { page }); 
    await And('user proceeds to the summary page to confirm details', null, { page }); 
    await And('user enters card number "4000 0000 0000 0002", expiry "12/26", CVC "999"', null, { page }); 
    await Then('a payment failure message should be displayed', null, { page }); 
  });

});

// == technical section ==

test.use({
  $test: [({}, use) => use(test), { scope: 'test', box: true }],
  $uri: [({}, use) => use('features\\GiftVoucher.feature'), { scope: 'test', box: true }],
  $bddFileData: [({}, use) => use(bddFileData), { scope: "test", box: true }],
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":11,"pickleLine":9,"tags":["@GiftVoucher","@timeout:180000","@smoke","@happy-path"],"steps":[{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given user navigates to the Phorest demo voucher page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":12,"gherkinStepLine":11,"keywordType":"Action","textWithKeyword":"When user selects a voucher amount of \"€50\"","stepMatchArguments":[{"group":{"start":33,"value":"\"€50\"","children":[{"start":34,"value":"€50","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":13,"gherkinStepLine":12,"keywordType":"Action","textWithKeyword":"And user verifies 'Send to me' tab is selected","stepMatchArguments":[]},{"pwStepLine":14,"gherkinStepLine":13,"keywordType":"Action","textWithKeyword":"And user enters email, forename \"Phorest\" and surname \"Test\"","stepMatchArguments":[{"group":{"start":28,"value":"\"Phorest\"","children":[{"start":29,"value":"Phorest","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":50,"value":"\"Test\"","children":[{"start":51,"value":"Test","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":15,"gherkinStepLine":14,"keywordType":"Action","textWithKeyword":"And user proceeds to the summary page to confirm details","stepMatchArguments":[]},{"pwStepLine":16,"gherkinStepLine":15,"keywordType":"Action","textWithKeyword":"And user enters card number \"4111 1111 1111 1111\", expiry \"12/26\", CVC \"999\"","stepMatchArguments":[{"group":{"start":24,"value":"\"4111 1111 1111 1111\"","children":[{"start":25,"value":"4111 1111 1111 1111","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":54,"value":"\"12/26\"","children":[{"start":55,"value":"12/26","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":67,"value":"\"999\"","children":[{"start":68,"value":"999","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":17,"gherkinStepLine":16,"keywordType":"Outcome","textWithKeyword":"Then the confirmation page should display the voucher value and number","stepMatchArguments":[]},{"pwStepLine":18,"gherkinStepLine":17,"keywordType":"Outcome","textWithKeyword":"And the user should receive a voucher email with a purchase receipt","stepMatchArguments":[]}]},
  {"pwTestLine":21,"pickleLine":20,"tags":["@GiftVoucher","@timeout:180000","@happy-path"],"steps":[{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given user navigates to the Phorest demo voucher page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":22,"gherkinStepLine":22,"keywordType":"Action","textWithKeyword":"When user selects a voucher amount of \"€100\"","stepMatchArguments":[{"group":{"start":33,"value":"\"€100\"","children":[{"start":34,"value":"€100","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":23,"gherkinStepLine":23,"keywordType":"Action","textWithKeyword":"And user selects 'Send to someone else' tab","stepMatchArguments":[]},{"pwStepLine":24,"gherkinStepLine":24,"keywordType":"Action","textWithKeyword":"And user enters email, forename \"Phorest\", surname \"Test\", recipient email and a message","stepMatchArguments":[{"group":{"start":28,"value":"\"Phorest\"","children":[{"start":29,"value":"Phorest","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":47,"value":"\"Test\"","children":[{"start":48,"value":"Test","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":25,"gherkinStepLine":25,"keywordType":"Action","textWithKeyword":"And user proceeds to the summary page to confirm details","stepMatchArguments":[]},{"pwStepLine":26,"gherkinStepLine":26,"keywordType":"Action","textWithKeyword":"And user enters card number \"4111 1111 1111 1111\", expiry \"12/26\", CVC \"999\"","stepMatchArguments":[{"group":{"start":24,"value":"\"4111 1111 1111 1111\"","children":[{"start":25,"value":"4111 1111 1111 1111","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":54,"value":"\"12/26\"","children":[{"start":55,"value":"12/26","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":67,"value":"\"999\"","children":[{"start":68,"value":"999","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":27,"gherkinStepLine":27,"keywordType":"Outcome","textWithKeyword":"Then the confirmation page should display the voucher value and number","stepMatchArguments":[]},{"pwStepLine":28,"gherkinStepLine":28,"keywordType":"Outcome","textWithKeyword":"And the user should receive a voucher email with a purchase receipt","stepMatchArguments":[]}]},
  {"pwTestLine":31,"pickleLine":31,"tags":["@GiftVoucher","@timeout:180000","@happy-path"],"steps":[{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given user navigates to the Phorest demo voucher page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":32,"gherkinStepLine":33,"keywordType":"Action","textWithKeyword":"When user selects a voucher amount of \"€150\"","stepMatchArguments":[{"group":{"start":33,"value":"\"€150\"","children":[{"start":34,"value":"€150","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":33,"gherkinStepLine":34,"keywordType":"Action","textWithKeyword":"And user selects 'Send to someone else' tab","stepMatchArguments":[]},{"pwStepLine":34,"gherkinStepLine":35,"keywordType":"Action","textWithKeyword":"And user enters email, forename \"Phorest\", surname \"Test\" and recipient email without a message","stepMatchArguments":[{"group":{"start":28,"value":"\"Phorest\"","children":[{"start":29,"value":"Phorest","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":47,"value":"\"Test\"","children":[{"start":48,"value":"Test","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":35,"gherkinStepLine":36,"keywordType":"Action","textWithKeyword":"And user proceeds to the summary page to confirm details","stepMatchArguments":[]},{"pwStepLine":36,"gherkinStepLine":37,"keywordType":"Action","textWithKeyword":"And user enters card number \"4111 1111 1111 1111\", expiry \"12/26\", CVC \"999\"","stepMatchArguments":[{"group":{"start":24,"value":"\"4111 1111 1111 1111\"","children":[{"start":25,"value":"4111 1111 1111 1111","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":54,"value":"\"12/26\"","children":[{"start":55,"value":"12/26","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":67,"value":"\"999\"","children":[{"start":68,"value":"999","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":37,"gherkinStepLine":38,"keywordType":"Outcome","textWithKeyword":"Then the confirmation page should display the voucher value and number","stepMatchArguments":[]},{"pwStepLine":38,"gherkinStepLine":39,"keywordType":"Outcome","textWithKeyword":"And the user should receive a voucher email with a purchase receipt","stepMatchArguments":[]}]},
  {"pwTestLine":41,"pickleLine":42,"tags":["@GiftVoucher","@timeout:180000","@happy-path"],"steps":[{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given user navigates to the Phorest demo voucher page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":42,"gherkinStepLine":44,"keywordType":"Action","textWithKeyword":"When user selects a custom voucher amount of \"€200\"","stepMatchArguments":[{"group":{"start":40,"value":"\"€200\"","children":[{"start":41,"value":"€200","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":43,"gherkinStepLine":45,"keywordType":"Action","textWithKeyword":"And user verifies 'Send to me' tab is selected","stepMatchArguments":[]},{"pwStepLine":44,"gherkinStepLine":46,"keywordType":"Action","textWithKeyword":"And user enters email, forename \"Phorest\" and surname \"Test\"","stepMatchArguments":[{"group":{"start":28,"value":"\"Phorest\"","children":[{"start":29,"value":"Phorest","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":50,"value":"\"Test\"","children":[{"start":51,"value":"Test","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":45,"gherkinStepLine":47,"keywordType":"Action","textWithKeyword":"And user proceeds to the summary page to confirm details","stepMatchArguments":[]},{"pwStepLine":46,"gherkinStepLine":48,"keywordType":"Action","textWithKeyword":"And user enters card number \"4111 1111 1111 1111\", expiry \"12/26\", CVC \"999\"","stepMatchArguments":[{"group":{"start":24,"value":"\"4111 1111 1111 1111\"","children":[{"start":25,"value":"4111 1111 1111 1111","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":54,"value":"\"12/26\"","children":[{"start":55,"value":"12/26","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":67,"value":"\"999\"","children":[{"start":68,"value":"999","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":47,"gherkinStepLine":49,"keywordType":"Outcome","textWithKeyword":"Then the confirmation page should display the voucher value and number","stepMatchArguments":[]},{"pwStepLine":48,"gherkinStepLine":50,"keywordType":"Outcome","textWithKeyword":"And the user should receive a voucher email with a purchase receipt","stepMatchArguments":[]}]},
  {"pwTestLine":51,"pickleLine":53,"tags":["@GiftVoucher","@timeout:180000","@happy-path"],"steps":[{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given user navigates to the Phorest demo voucher page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":52,"gherkinStepLine":54,"keywordType":"Action","textWithKeyword":"When user selects a voucher amount of \"€50\"","stepMatchArguments":[{"group":{"start":33,"value":"\"€50\"","children":[{"start":34,"value":"€50","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":53,"gherkinStepLine":55,"keywordType":"Action","textWithKeyword":"And user verifies 'Send to me' tab is selected","stepMatchArguments":[]},{"pwStepLine":54,"gherkinStepLine":56,"keywordType":"Action","textWithKeyword":"And user enters email, forename \"Phorest\" and surname \"Test\"","stepMatchArguments":[{"group":{"start":28,"value":"\"Phorest\"","children":[{"start":29,"value":"Phorest","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":50,"value":"\"Test\"","children":[{"start":51,"value":"Test","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":55,"gherkinStepLine":57,"keywordType":"Action","textWithKeyword":"And user proceeds to the summary page, clicks edit and updates the voucher amount to be \"€100\"","stepMatchArguments":[{"group":{"start":84,"value":"\"€100\"","children":[{"start":85,"value":"€100","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":56,"gherkinStepLine":58,"keywordType":"Action","textWithKeyword":"And user enters card number \"4111 1111 1111 1111\", expiry \"12/26\", CVC \"999\"","stepMatchArguments":[{"group":{"start":24,"value":"\"4111 1111 1111 1111\"","children":[{"start":25,"value":"4111 1111 1111 1111","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":54,"value":"\"12/26\"","children":[{"start":55,"value":"12/26","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":67,"value":"\"999\"","children":[{"start":68,"value":"999","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":57,"gherkinStepLine":59,"keywordType":"Outcome","textWithKeyword":"Then the confirmation page should display the voucher value and number","stepMatchArguments":[]},{"pwStepLine":58,"gherkinStepLine":60,"keywordType":"Outcome","textWithKeyword":"And the user should receive a voucher email with a purchase receipt","stepMatchArguments":[]}]},
  {"pwTestLine":61,"pickleLine":63,"tags":["@GiftVoucher","@timeout:180000","@validation"],"steps":[{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given user navigates to the Phorest demo voucher page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":62,"gherkinStepLine":64,"keywordType":"Action","textWithKeyword":"When user selects a voucher amount of \"€50\"","stepMatchArguments":[{"group":{"start":33,"value":"\"€50\"","children":[{"start":34,"value":"€50","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":63,"gherkinStepLine":65,"keywordType":"Action","textWithKeyword":"And user verifies 'Send to me' tab is selected","stepMatchArguments":[]},{"pwStepLine":64,"gherkinStepLine":66,"keywordType":"Action","textWithKeyword":"And user enters invalid email \"invalid-email\", forename \"Phorest\" and surname \"Test\"","stepMatchArguments":[{"group":{"start":26,"value":"\"invalid-email\"","children":[{"start":27,"value":"invalid-email","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":52,"value":"\"Phorest\"","children":[{"start":53,"value":"Phorest","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":74,"value":"\"Test\"","children":[{"start":75,"value":"Test","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":65,"gherkinStepLine":67,"keywordType":"Outcome","textWithKeyword":"Then an error message should be displayed indicating the email format is invalid","stepMatchArguments":[]},{"pwStepLine":66,"gherkinStepLine":68,"keywordType":"Outcome","textWithKeyword":"And the user should not be able to proceed to the summary page","stepMatchArguments":[]}]},
  {"pwTestLine":69,"pickleLine":71,"tags":["@GiftVoucher","@timeout:180000","@validation"],"steps":[{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given user navigates to the Phorest demo voucher page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":70,"gherkinStepLine":72,"keywordType":"Action","textWithKeyword":"When user selects a voucher amount of \"€100\"","stepMatchArguments":[{"group":{"start":33,"value":"\"€100\"","children":[{"start":34,"value":"€100","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":71,"gherkinStepLine":73,"keywordType":"Action","textWithKeyword":"And user selects 'Send to someone else' tab","stepMatchArguments":[]},{"pwStepLine":72,"gherkinStepLine":74,"keywordType":"Outcome","textWithKeyword":"Then the user should not be able to proceed to the summary page","stepMatchArguments":[]}]},
  {"pwTestLine":75,"pickleLine":77,"tags":["@GiftVoucher","@timeout:180000","@validation"],"steps":[{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given user navigates to the Phorest demo voucher page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":76,"gherkinStepLine":79,"keywordType":"Action","textWithKeyword":"When user selects a custom voucher amount of \"€10\"","stepMatchArguments":[{"group":{"start":40,"value":"\"€10\"","children":[{"start":41,"value":"€10","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":77,"gherkinStepLine":80,"keywordType":"Action","textWithKeyword":"And user verifies 'Send to me' tab is selected","stepMatchArguments":[]},{"pwStepLine":78,"gherkinStepLine":81,"keywordType":"Action","textWithKeyword":"And user enters email, forename \"Phorest\" and surname \"Test\"","stepMatchArguments":[{"group":{"start":28,"value":"\"Phorest\"","children":[{"start":29,"value":"Phorest","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":50,"value":"\"Test\"","children":[{"start":51,"value":"Test","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":79,"gherkinStepLine":82,"keywordType":"Outcome","textWithKeyword":"Then an error message should be displayed indicating the custom amount is invalid","stepMatchArguments":[]},{"pwStepLine":80,"gherkinStepLine":83,"keywordType":"Outcome","textWithKeyword":"And the user should not be able to proceed to the summary page","stepMatchArguments":[]}]},
  {"pwTestLine":83,"pickleLine":86,"tags":["@GiftVoucher","@timeout:180000","@negative"],"steps":[{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given user navigates to the Phorest demo voucher page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":84,"gherkinStepLine":88,"keywordType":"Action","textWithKeyword":"When user selects a voucher amount of \"€50\"","stepMatchArguments":[{"group":{"start":33,"value":"\"€50\"","children":[{"start":34,"value":"€50","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":85,"gherkinStepLine":89,"keywordType":"Action","textWithKeyword":"And user verifies 'Send to me' tab is selected","stepMatchArguments":[]},{"pwStepLine":86,"gherkinStepLine":90,"keywordType":"Action","textWithKeyword":"And user enters email, forename \"Phorest\" and surname \"Test\"","stepMatchArguments":[{"group":{"start":28,"value":"\"Phorest\"","children":[{"start":29,"value":"Phorest","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":50,"value":"\"Test\"","children":[{"start":51,"value":"Test","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":87,"gherkinStepLine":91,"keywordType":"Action","textWithKeyword":"And user proceeds to the summary page to confirm details","stepMatchArguments":[]},{"pwStepLine":88,"gherkinStepLine":92,"keywordType":"Action","textWithKeyword":"And user enters card number \"4000 0000 0000 0002\", expiry \"12/26\", CVC \"999\"","stepMatchArguments":[{"group":{"start":24,"value":"\"4000 0000 0000 0002\"","children":[{"start":25,"value":"4000 0000 0000 0002","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":54,"value":"\"12/26\"","children":[{"start":55,"value":"12/26","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":67,"value":"\"999\"","children":[{"start":68,"value":"999","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":89,"gherkinStepLine":93,"keywordType":"Outcome","textWithKeyword":"Then a payment failure message should be displayed","stepMatchArguments":[]}]},
]; // bdd-data-end